language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
before_script:
  - sudo apt-get -y install python
script:
  - mv file_lists.txt ori.txt
  - python generate_file_lists.py
  - diff ori.txt file_lists.txt
  - mv src/function src/a
  - sh travis-ci.sh src
after_script:
  - cat myerrorfile
